project:
  type: website
  output-dir: docs

website:
  title: "My phenomenal first website!"
  navbar:
    right: 
      - text: "About Me"
        href: about.qmd
      - text: "Data Viz"
        menu: 
         - text: "Species of Rodent"
           href: rodent_data.qmd
         - text: "Coffee ratings"
           href: coffee.qmd
        


format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

  
