project:
  type: website
  output-dir: docs

website:
  title: "Natalie Sullivan Wu"
  navbar:
    right: 
      - text: "Resources"
        href: resources.qmd
      - text: "Data Viz"
        menu: 
         - text: "Project 1 -- Species of Rodent"
           href: rodent_data.qmd
         - text: "Project 1 -- Coffee ratings"
           href: coffee.qmd
         - text: "Project 2 -- Spotify Tracks"
           href: miniproject2.qmd
         - text: "Project 3 -- Probability of Shared Birthdays"
           href: project3.qmd
         - text: "Project 4 -- SQL"
           href: project4.qmd
         - text: "Project 5 -- Presentation About My Projects"
           href: project5.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

  
